
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    container_name: rails_api
    build:
      context: "."
      dockerfile: ./container/backend/Dockerfile
    volumes:
      - ./api:/usr/src/backend
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db
volumes:
  postgres_data:
